import React, { useEffect, useRef, useState } from 'react';
import { Loader2, Plus, ArrowRight, RefreshCw } from 'lucide-react';
import BrandButton from '@/components/operator/BrandButton';
import useOperatorChat from '@/components/whatsapp/useOperatorChat';
import OperatorMessage from '@/components/whatsapp/OperatorMessage';
export default function OperatorChat({ userId, compact = false }) {
  const chat=useOperatorChat(userId), [text,setText]=useState(''), logRef=useRef(null);
  useEffect(()=>{if(compact&&logRef.current)logRef.current.scrollTop=logRef.current.scrollHeight;},[compact,chat.messages.length,chat.busy]);
  async function submit(e){e.preventDefault();const value=text.trim();if(!value)return;if(await chat.send(value))setText('');}
  return <section className={compact ? 'flex flex-1 min-h-0 flex-col bg-card' : 'operator-panel'}><header className="p-5 border-b flex flex-wrap items-center justify-between gap-3">{!compact && <div><h2 className="font-bold text-lg">Talk to your operator</h2><p className="text-xs text-muted-foreground mt-1">An in-app conversation with the same agent used by WhatsApp.</p></div>}<div className="flex gap-2"><BrandButton variant="outline" disabled={chat.busy} onClick={chat.newChat}><Plus/>New chat</BrandButton><button className="p-3 rounded-lg border" aria-label="Refresh conversations" onClick={chat.refresh} disabled={chat.busy}><RefreshCw className="h-4 w-4"/></button></div></header>
    {chat.conversations.length>0&&<label className="field-label p-5 border-b">Conversation<select className="operator-input" value={chat.id||''} onChange={e=>chat.select(e.target.value)} disabled={chat.busy}>{chat.conversations.map(c=><option key={c.id} value={c.id}>{c.metadata?.name||'Operator chat'} · {c.created_date?new Date(c.created_date).toLocaleString():c.id.slice(-6)}</option>)}</select></label>}
    {chat.error&&<p role="alert" className="m-5 p-3 border rounded-lg text-sm">{chat.error}</p>}
    <div ref={logRef} role="log" aria-label="Operator messages" aria-live="polite" className={compact ? 'min-h-0 flex-1 overflow-y-auto p-5 space-y-4' : 'h-96 overflow-y-auto p-5 space-y-4'}>{chat.loading?<p className="text-sm flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin"/>Loading conversations…</p>:chat.messages.length?chat.messages.filter(m=>['assistant','user'].includes(m.role)).map((m,i)=><OperatorMessage key={m.id||i} message={m}/>):<div className="text-sm text-muted-foreground py-12 text-center"><p>Ask about your tasks or paired computers.</p><p className="mt-2">For example: “Which computers are online?”</p></div>}{chat.busy&&<p role="status" className="text-sm flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin"/>Sending…</p>}</div>
    <form onSubmit={submit} className="p-5 border-t space-y-3 bg-card"><label className="field-label">Message your operator<textarea className="operator-input resize-y" rows={compact?2:3} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(compact&&e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} maxLength={4000} placeholder="Check my task queue…" required disabled={chat.busy}/></label><div className="flex flex-wrap justify-between items-center gap-3"><p className="text-xs text-muted-foreground">Never send passwords, recovery codes, or payment details.</p><BrandButton className="!rounded-xl" type="submit" disabled={chat.busy||chat.loading||!text.trim()}>Send message<ArrowRight/></BrandButton></div></form>
  </section>;
}