import React, { useState } from 'react';
import { Search, FileCode2, Download, FolderOpen, Loader2 } from 'lucide-react';
import BrandButton from '@/components/operator/BrandButton';
export default function ArchiveFiles({ zip }) {
  const [search,setSearch]=useState('');
  const files=(zip.archive?.files||[]).filter(f=>f.name.toLowerCase().includes(search.toLowerCase()));
  return <section className="operator-panel"><header className="p-5 border-b flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><FolderOpen className="w-5 h-5 shrink-0"/><div className="min-w-0"><h2 className="font-semibold text-sm truncate">{zip.name||'ZIP workspace'}</h2><p className="text-xs text-muted-foreground mt-1">{zip.archive ? `${zip.archive.files.length} files · source is never executed` : 'Choose a source package or open your own ZIP'}</p></div></div>{zip.archive&&<BrandButton variant="outline" disabled={zip.busy} onClick={zip.extractAll}><Download/>{zip.busy?'Extracting…':'Extract to folder'}</BrandButton>}</header>
    {zip.busy&&!zip.archive?<div className="p-16 flex justify-center gap-3 text-sm"><Loader2 className="w-5 h-5 animate-spin"/>Reading archive…</div>:zip.archive?<div className="grid lg:grid-cols-[280px_minmax(0,1fr)]"><div className="border-b lg:border-b-0 lg:border-r"><label className="relative block m-3"><Search className="w-4 h-4 absolute left-3 top-3"/><input aria-label="Search archive files" className="operator-input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a file…"/></label><div className="h-56 lg:h-[480px] overflow-y-auto p-2" aria-label="Archive files">{files.map(file=><button key={file.name} disabled={zip.busy} onClick={()=>zip.open(file)} className={`w-full text-left p-2.5 rounded-lg flex gap-2 items-start text-xs ${zip.selected?.name===file.name?'bg-muted font-semibold':'hover:bg-muted'}`}><FileCode2 className="h-3.5 w-3.5 shrink-0 mt-0.5 text-muted-foreground"/><span className="break-all">{file.name}</span></button>)}{!files.length&&<p className="p-5 text-xs text-muted-foreground">No matching files.</p>}</div></div><div className="min-w-0"><div className="p-4 border-b min-h-16 flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-mono break-all">{zip.selected?.name||'Select a file to preview'}</p>{zip.selected&&<button disabled={zip.fileBusy||zip.busy} onClick={zip.download} className="brand-link flex gap-2 items-center"><Download className="w-4 h-4"/>Download file</button>}</div>{zip.fileBusy?<div className="p-16 flex justify-center"><Loader2 className="w-5 h-5 animate-spin"/></div>:zip.selected?<pre className="p-5 text-xs font-mono whitespace-pre-wrap break-words h-[480px] overflow-auto bg-[#FAFAFA]">{zip.preview}</pre>:<div className="flex flex-col gap-3 items-center justify-center h-64 lg:h-[480px] text-muted-foreground"><FileCode2 className="w-9 h-9"/><p className="text-sm">Inspect first. Connect with confidence.</p><p className="text-xs">Preview source or safely extract individual files.</p></div>}</div></div>:<div className="text-center px-6 py-14 text-sm text-muted-foreground">Your browser reads and extracts ZIPs locally. No AI credits needed.</div>}
  </section>;
}