import React, { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ShieldCheck, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import BrandButton from '@/components/operator/BrandButton';
export default function AuditPanel() {
  const client = useQueryClient();
  const {data=[],isPending,error,refetch} = useQuery({queryKey:['operator-audits'],queryFn:()=>base44.entities.OperatorAudit.list('-created_date',30),refetchInterval:30000});
  const [busy,setBusy] = useState(false), [runError,setRunError] = useState('');
  async function run() {setBusy(true);setRunError('');try {await base44.functions.invoke('auditOperator',{source:'manual'});await client.invalidateQueries({queryKey:['operator-audits']});}catch(e){setRunError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
  return <div className="space-y-6"><section className="operator-panel p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Operator health audit</h2><p className="text-sm text-muted-foreground mt-2">Checks recent tasks, schedules, commands, and paired devices. Expired, unstarted commands are safely closed; other issues need review.</p></div><BrandButton onClick={run} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ShieldCheck/>}{busy?'Auditing…':'Run audit'}</BrandButton></div><p className="text-xs text-muted-foreground mt-4">Scheduled every 15 minutes when automation is available. This does not inspect your OS, third-party accounts, or source code.</p>{runError&&<p role="alert" className="mt-4 text-sm">{runError}</p>}</section>{error&&<div role="alert" className="operator-panel p-5 text-sm">Could not load audits. <button className="underline" onClick={()=>refetch()}>Retry</button></div>}{isPending?<p className="text-sm flex items-center gap-2"><Loader2 className="w-4 h-4 animate-spin"/>Loading audits…</p>:!data.length?<div className="operator-panel p-6 text-sm text-muted-foreground">No audits yet. Run one to check the operator now.</div>:data.map(a=><article key={a.id} className="operator-panel p-6"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold">{a.status==='healthy'?'Healthy':'Needs attention'}</h3><p className="text-xs text-muted-foreground mt-1">{new Date(a.created_date).toLocaleString()} · {a.source} · {a.healed_count||0} expired commands closed</p></div><span className="neutral-pill">{a.findings?.length||0} findings</span></div><p className="text-sm mt-4">{a.summary}</p><ul className="mt-4 space-y-3">{(a.findings||[]).map((f,i)=><li key={i} className="border rounded-lg p-3 text-sm"><strong>{f.message}</strong><p className="text-muted-foreground mt-1">{f.recommendation}</p></li>)}</ul></article>)}</div>;
}