import React, { useState } from 'react';
import { ArrowRight, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import BrandButton from '@/components/operator/BrandButton';
const actions={screen_info:'Read screen dimensions',open_url:'Open a website',click:'Click a position',type_text:'Type text',press_key:'Press keys',scroll:'Scroll',browser_health:'Check Cloud Browser',browser_start:'Start browser session',browser_action:'Run browser action',browser_close:'Close browser session'};
export default function ComputerActionForm({ devices, onSent }) {
  const [deviceId,setDeviceId]=useState(''),[action,setAction]=useState('screen_info'),[args,setArgs]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const online=devices.filter(d=>d.online&&d.enabled&&!d.revoked),selected=deviceId?online.find(d=>d.id===deviceId):online[0];
  const field=(key,value)=>setArgs(old=>({...old,[key]:value}));
  async function send(e){e.preventDefault();if(!selected)return;setBusy(true);setError('');setMessage('');try{const {data}=await base44.functions.invoke('computerControl',{operation:'send',device_id:selected.id,action,arguments:args});setMessage('Action queued. The receipt below will show whether it executed.');await onSent();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
  return <section className="operator-panel p-6"><h2 className="text-lg font-bold">Send a computer action</h2><p className="mt-2 text-sm text-muted-foreground">Direct control uses the companion, not an AI integration. Action inputs are saved in workspace history—do not send passwords here.</p><form onSubmit={send} className="grid sm:grid-cols-2 gap-4 mt-5"><label className="field-label">Computer<select className="operator-input" value={selected?.id||''} onChange={e=>setDeviceId(e.target.value)} disabled={!online.length}><option value="" disabled>{online.length?'Choose an online computer':'Start a paired companion first'}</option>{online.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label className="field-label">Action<select className="operator-input" value={action} onChange={e=>{setAction(e.target.value);setArgs({});}}>{Object.entries(actions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    {action==='open_url'&&<label className="field-label sm:col-span-2">Website address<input required type="url" className="operator-input" onChange={e=>field('url',e.target.value)}/></label>}
    {action==='click'&&['x','y'].map(key=><label key={key} className="field-label">{key.toUpperCase()} coordinate<input required type="number" min="0" max="20000" step="1" className="operator-input" onChange={e=>field(key,Number(e.target.value))}/></label>)}
    {action==='type_text'&&<label className="field-label sm:col-span-2">Text to type (ASCII)<textarea required maxLength={1000} className="operator-input" onChange={e=>field('text',e.target.value)}/></label>}
    {action==='press_key'&&<label className="field-label sm:col-span-2">Key combination<input required maxLength={100} placeholder="ctrl+l or enter" className="operator-input" onChange={e=>field('keys',e.target.value)}/></label>}
    {action==='scroll'&&<label className="field-label">Scroll notches (negative = down)<input required type="number" min="-30" max="30" step="1" className="operator-input" onChange={e=>field('amount',Number(e.target.value))}/></label>}
    {['browser_action','browser_close'].includes(action)&&<label className="field-label sm:col-span-2">Session ID<input required maxLength={100} className="operator-input" onChange={e=>field('session_id',e.target.value)}/></label>}
    {action==='browser_action'&&<><label className="field-label">Browser action<select required className="operator-input" value={args.action_type||''} onChange={e=>field('action_type',e.target.value)}><option value="">Choose action</option>{['goto','click','fill','press','scroll'].map(value=><option key={value}>{value}</option>)}</select></label><label className="field-label">Selector<input className="operator-input" maxLength={500} required={['click','fill'].includes(args.action_type)} onChange={e=>field('selector',e.target.value)}/></label><label className="field-label sm:col-span-2">Value / URL<input className="operator-input" maxLength={2000} required={['goto','fill','press','scroll'].includes(args.action_type)} onChange={e=>field('value',e.target.value)}/></label></>}
    <div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-muted-foreground">Queued actions expire after 2 minutes. Desktop screenshots are available through local MCP.</p><BrandButton type="submit" disabled={busy||!selected}>{busy?<Loader2 className="animate-spin"/>:<ArrowRight/>}Send action</BrandButton></div>{error&&<p role="alert" className="text-sm sm:col-span-2">{error}</p>}{message&&<p role="status" className="text-sm sm:col-span-2">{message}</p>}</form></section>;
}