import React, { useState } from 'react';
import { Monitor, Plus, Pause, Play, ShieldCheck } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import BrandButton from '@/components/operator/BrandButton';
import PairDeviceForm from '@/components/operator/PairDeviceForm';
import CompanionSetup from '@/components/operator/CompanionSetup';
import ComputerActionForm from '@/components/operator/ComputerActionForm';
import PhoneActionForm from '@/components/operator/PhoneActionForm';
import CommandReceipts from '@/components/operator/CommandReceipts';
export default function DevicePanel({ data }) {
  const [pair,setPair]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function manage(operation,device){if(operation==='revoke'&&!window.confirm('Revoke this computer’s remote pairing? The companion must be paired again to reconnect.'))return;setBusy(true);setError('');try{await base44.functions.invoke('operatorDevices',{operation,device_id:device.id});await data.refresh();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
  return <div className="space-y-6"><section className="operator-panel p-6"><div className="flex flex-wrap justify-between gap-4 items-center"><div><h2 className="font-bold text-xl">Your computers</h2><p className="text-sm text-muted-foreground mt-2">Pair once. Keep the companion running. Let your approved agents work.</p></div><BrandButton onClick={()=>setPair(true)}><Plus/>Pair computer</BrandButton></div>{error&&<p role="alert" className="mt-5 text-sm">{error}</p>}<div className="mt-6 space-y-4">{!data.devices.length?<div className="border rounded-xl p-7 flex gap-4 items-center"><Monitor className="w-8 h-8 text-muted-foreground"/><p className="text-sm text-muted-foreground">No computer paired yet. Publish the app, then download a pairing kit.</p></div>:data.devices.map(device=><div key={device.id} className="border rounded-xl p-4 flex flex-wrap items-center gap-4"><Monitor className="w-5 h-5"/><div className="flex-1 min-w-32"><h3 className="font-semibold text-sm">{device.name}</h3><p className="text-xs text-muted-foreground mt-1">{device.platform||'Awaiting first check-in'} · {device.input_allowed?'Input enabled':'Input disabled'}</p><p className="text-[10px] text-muted-foreground mt-1">Pairing expires {new Date(device.expires_at).toLocaleDateString()}</p></div><span className="neutral-pill">{device.revoked?'Revoked':Date.parse(device.expires_at)<Date.now()?'Pairing expired':!device.enabled?'Paused':device.online?'Online':'Offline'}</span>{!device.revoked&&<><BrandButton variant="outline" disabled={busy} onClick={()=>manage(device.enabled?'pause':'resume',device)}>{device.enabled?<Pause/>:<Play/>}{device.enabled?'Pause':'Resume'}</BrandButton><button className="brand-link" disabled={busy} onClick={()=>manage('revoke',device)}>Revoke</button></>}</div>)}</div></section><ComputerActionForm devices={data.devices} onSent={data.refresh}/><PhoneActionForm devices={data.devices} onSent={data.refresh}/><CommandReceipts commands={data.commands}/><CompanionSetup/><div className="text-xs text-muted-foreground flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/>Pairing does not install software remotely. Run the downloaded companion yourself to authorize this computer.</div>{pair&&<PairDeviceForm open onClose={()=>setPair(false)} onSaved={data.refresh}/>}</div>;
}