import React from 'react';
import { Monitor, Globe, Network } from 'lucide-react';
const active = row => ['queued','running'].includes(row.status) && (!row.expires_at || Date.parse(row.expires_at) > Date.now());
function WorkLane({ title, Icon, tasks, commands, empty }) {
  const rows=[...tasks.map(t=>({id:`task-${t.id}`,title:t.title,status:t.status,when:t.updated_date||t.created_date,kind:'Task'})),...commands.map(c=>({id:`command-${c.id}`,title:c.action.replaceAll('_',' '),status:c.status,when:c.updated_date||c.created_date,kind:'Action'}))].sort((a,b)=>Date.parse(b.when||0)-Date.parse(a.when||0));
  return <section className="operator-panel min-w-0"><header className="p-5 border-b border-border flex items-center gap-3"><Icon className="h-5 w-5"/><div><h2 className="font-bold">{title}</h2><p className="text-xs text-muted-foreground">{tasks.filter(active).length} active tasks · {commands.filter(active).length} pending actions</p></div></header>{!rows.length?<p className="p-5 text-sm text-muted-foreground">{empty}</p>:<ul className="divide-y divide-border">{rows.slice(0,12).map(row=><li key={row.id} className="flex items-start gap-3 p-4 text-sm"><span className="neutral-pill shrink-0 capitalize">{row.status}</span><span className="min-w-0 flex-1 break-words">{row.title}<span className="block text-xs text-muted-foreground mt-1">{row.kind} · {row.when?new Date(row.when).toLocaleString():'Time unavailable'}</span></span></li>)}</ul>}</section>;
}
export default function LiveOperations({ data }) {
  const computers=data.devices.filter(d=>d.enabled&&!d.revoked&&d.online);
  const computerTasks=data.tasks.filter(t=>t.target==='computer');
  const cloudTasks=data.tasks.filter(t=>t.target==='cloud_browser');
  const computerCommands=data.commands.filter(c=>!c.action.startsWith('browser_')&&!c.action.startsWith('phone_'));
  const browserCommands=data.commands.filter(c=>c.action.startsWith('browser_'));
  const phoneCommands=data.commands.filter(c=>c.action.startsWith('phone_'));
  return <div className="space-y-4" aria-label="Unified operations monitor"><div className="operator-panel p-5 flex items-start gap-3"><Network className="h-5 w-5 shrink-0"/><div><h2 className="font-bold">Agent swarm visibility</h2><p className="text-sm text-muted-foreground mt-1">No specialist swarm workers are connected yet. This view shows actual task reports and device receipts, not agent reasoning or activity inside unconnected cloud apps.</p><p className="text-xs text-muted-foreground mt-2">{computers.length} online paired computer{computers.length===1?'':'s'} · {data.devices.length} paired · companion presence updates about every 8 seconds</p></div></div><div className="grid gap-4 lg:grid-cols-2"><WorkLane title="Computer" Icon={Monitor} tasks={computerTasks} commands={computerCommands} empty="No computer work has been reported."/><WorkLane title="Cloud browser" Icon={Globe} tasks={cloudTasks} commands={browserCommands} empty="No cloud-browser work has been reported."/></div><section className="operator-panel p-5"><h2 className="font-bold">Connected phones</h2><p className="text-xs text-muted-foreground mt-1">Phone actions run through a paired computer; this is not a direct live phone connection.</p>{phoneCommands.length?<ul className="divide-y divide-border mt-3">{phoneCommands.slice(0,6).map(c=><li key={c.id} className="flex justify-between gap-3 py-3 text-sm"><span className="capitalize">{c.action.replaceAll('_',' ')}</span><span className="neutral-pill capitalize">{c.status}</span></li>)}</ul>:<p className="text-sm text-muted-foreground mt-3">No phone actions reported.</p>}</section></div>;
}