import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { base44 } from '@/api/base44Client';
import { appParams } from '@/lib/app-params';
import BrandButton from '@/components/operator/BrandButton';
import downloadCompanion from '@/components/operator/companionBundle';
export default function PairDeviceForm({ open, onClose, onSaved }) {
  const [name,setName]=useState('My computer'),[url,setUrl]=useState(''),[engine,setEngine]=useState(''),[key,setKey]=useState(''),[bundle,setBundle]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function pair(e){e.preventDefault();setBusy(true);setError('');try{const origin=new URL(url);if(origin.protocol!=='https:'||origin.username||origin.password)throw new Error('Paste the HTTPS address of your published app.');if(!!engine!==!!key)throw new Error('Provide both the browser engine address and key, or leave both empty.');if(engine){const u=new URL(engine);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw new Error('The browser engine needs HTTPS, except localhost.');}const {data}=await base44.functions.invoke('operatorDevices',{operation:'create',name});const config={endpoint:`${origin.origin}/api/apps/${appParams.appId}/functions/deviceBridge`,device_id:data.device.id,token:data.token,...(engine?{browser_url:engine,browser_key:key}:{})};setBundle(config);downloadCompanion(config);await onSaved();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
  return <Dialog open={open} onOpenChange={value=>!value&&!busy&&onClose()}><DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Pair your computer</DialogTitle><DialogDescription>Publish the app first. Download the companion, then run it on the computer you want agents to operate.</DialogDescription></DialogHeader>{bundle?<div className="space-y-5"><p className="text-sm">Your pairing kit is ready. Extract it and run the launcher for your operating system. The device appears online after its first authenticated check-in.</p><p className="text-sm font-semibold">Keep this download private: it contains a device credential that expires in 30 days.</p><BrandButton onClick={()=>downloadCompanion(bundle)}><Download/>Download pairing kit again</BrandButton><BrandButton variant="outline" onClick={onClose}>Done</BrandButton></div>:<form onSubmit={pair} className="grid gap-4"><label className="field-label">Computer name<input className="operator-input" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/></label><label className="field-label">Published app address<input type="url" className="operator-input" value={url} onChange={e=>setUrl(e.target.value)} required/><span className="font-normal text-xs text-muted-foreground">Copy the live address after publishing, not the builder preview address.</span></label><details><summary className="text-sm font-semibold py-2">Optional: connect your Cloud Browser engine</summary><div className="grid gap-4 mt-3"><label className="field-label">Engine address<input type="url" className="operator-input" value={engine} onChange={e=>setEngine(e.target.value)}/></label><label className="field-label">Engine API key<input type="password" autoComplete="off" className="operator-input" value={key} onChange={e=>setKey(e.target.value)}/></label><p className="text-xs text-muted-foreground">These engine credentials go only into your downloaded kit, not the app database.</p></div></details><p className="text-xs text-muted-foreground">Only pair a computer you own or administer. The launcher asks permission before allowing mouse and keyboard control.</p>{error&&<p role="alert" className="text-sm border p-3 rounded-lg">{error}</p>}<BrandButton type="submit" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Download/>}{busy?'Creating pairing…':'Pair & download companion'}</BrandButton></form>}</DialogContent></Dialog>;
}