import React, { useState } from 'react';
import { ArrowRight, Loader2, Smartphone } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import BrandButton from '@/components/operator/BrandButton';
const actions={phone_status:'Read phone status',phone_tap:'Tap screen',phone_swipe:'Swipe screen',phone_text:'Type basic text',phone_key:'Press phone button'};
export default function PhoneActionForm({ devices, onSent }) {
  const [deviceId,setDeviceId]=useState(''),[action,setAction]=useState('phone_status'),[args,setArgs]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const online=devices.filter(d=>d.online&&d.enabled&&!d.revoked),selected=deviceId?online.find(d=>d.id===deviceId):online[0];
  const field=(key,value)=>setArgs(old=>({...old,[key]:value}));
  async function send(e){e.preventDefault();if(!selected)return;setBusy(true);setError('');setMessage('');try{await base44.functions.invoke('computerControl',{operation:'send',device_id:selected.id,action,arguments:args});setMessage('Queued. See the action receipt below for the result.');await onSent();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}}
  return <section className="operator-panel p-6"><div className="flex items-center gap-3"><Smartphone className="h-5 w-5"/><h2 className="text-lg font-bold">Android phone control</h2></div><p className="mt-2 text-sm text-muted-foreground">Pair a computer using a fresh companion kit, install Android Platform Tools on it, and connect one Android phone by USB. Enable USB debugging and approve that computer on the phone. Older companion downloads need replacing. Open Strategic on your phone to control your computer from there, too.</p>
    <form onSubmit={send} className="grid sm:grid-cols-2 gap-4 mt-5"><label className="field-label">Paired computer<select className="operator-input" value={selected?.id||''} onChange={e=>setDeviceId(e.target.value)} disabled={!online.length}><option value="" disabled>{online.length?'Choose a computer':'Start a paired companion first'}</option>{online.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label className="field-label">Phone action<select className="operator-input" value={action} onChange={e=>{setAction(e.target.value);setArgs({});}}>{Object.entries(actions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    {action==='phone_tap'&&['x','y'].map(key=><label key={key} className="field-label">{key.toUpperCase()} coordinate<input required type="number" min="0" max="20000" step="1" className="operator-input" onChange={e=>field(key,Number(e.target.value))}/></label>)}
    {action==='phone_swipe'&&<>{['x1','y1','x2','y2'].map(key=><label key={key} className="field-label">{key.toUpperCase()} coordinate<input required type="number" min="0" max="20000" step="1" className="operator-input" onChange={e=>field(key,Number(e.target.value))}/></label>)}<label className="field-label sm:col-span-2">Duration (milliseconds)<input required type="number" min="100" max="2000" step="1" className="operator-input" onChange={e=>field('duration',Number(e.target.value))}/></label></>}
    {action==='phone_text'&&<label className="field-label sm:col-span-2">Text (letters, numbers, spaces)<input required maxLength={120} pattern="[A-Za-z0-9 ]+" className="operator-input" onChange={e=>field('text',e.target.value)}/></label>}
    {action==='phone_key'&&<label className="field-label sm:col-span-2">Button<select className="operator-input" required value={args.key||''} onChange={e=>field('key',e.target.value)}><option value="">Choose button</option><option value="home">Home</option><option value="back">Back</option><option value="app_switch">Recent apps</option></select></label>}
    <div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-muted-foreground">The phone must remain connected and authorized. Only control a phone you own or administer. Do not type passwords here; commands are saved in workspace history. iPhone screen control is not supported by this companion.</p><BrandButton type="submit" disabled={busy||!selected}>{busy?<Loader2 className="animate-spin"/>:<ArrowRight/>}Send action</BrandButton></div>{error&&<p role="alert" className="text-sm sm:col-span-2">{error}</p>}{message&&<p role="status" className="text-sm sm:col-span-2">{message}</p>}</form></section>;
}