import React from 'react';
import { Clock3, Plus, CalendarClock } from 'lucide-react';
import BrandButton from '@/components/operator/BrandButton';
import { cadenceLabels, targetLabels } from '@/components/operator/sourcePackages';
export default function ScheduleList({ schedules, onCreate, onUpdate, busy }) {
  return <div className="space-y-6"><div className="operator-panel p-5 flex gap-4"><Clock3 className="w-5 h-5 shrink-0 mt-1"/><div><h2 className="font-semibold text-sm">Set the cadence. Keep control.</h2><p className="mt-2 text-sm text-muted-foreground">Schedules add goals to the task queue. The five-minute queue check requires available automation credits; queued goals still need an execution connection. All times are UTC.</p></div></div>
    {schedules.length===0?<div className="operator-panel px-6 py-16 text-center"><CalendarClock className="w-10 h-10 mx-auto mb-5 text-muted-foreground"/><h2 className="font-semibold text-lg">Build a consistent routine</h2><p className="text-sm text-muted-foreground mt-2 mb-6">Save a recurring task and enable it when you’re ready.</p><BrandButton onClick={onCreate}><Plus/>Create schedule</BrandButton></div>:<div className="grid lg:grid-cols-2 gap-5">{schedules.map(schedule=><article key={schedule.id} className="brand-board"><div className="flex justify-between items-start"><div className="brand-board-icon"><Clock3 className="h-5 w-5"/></div><span className="neutral-pill">{schedule.enabled?'Enabled · credits required':'Paused'}</span></div><h3>{schedule.title}</h3><p className="whitespace-pre-wrap break-words">{schedule.instructions}</p><div className="mt-6 py-4 border-t border-b flex flex-wrap justify-between gap-3 text-xs"><span>{cadenceLabels[schedule.cron]}</span><code>{schedule.cron}</code></div><div className="flex items-center justify-between gap-3 mt-5"><span className="text-xs text-muted-foreground">{targetLabels[schedule.target]}</span><BrandButton variant="outline" disabled={busy} onClick={()=>onUpdate({id:schedule.id,enabled:!schedule.enabled})}>{schedule.enabled?'Pause schedule':'Enable schedule'}</BrandButton></div>{schedule.last_enqueued_at&&<p>Last queued {new Date(schedule.last_enqueued_at).toLocaleString()}</p>}</article>)}</div>}
    <p className="text-xs text-muted-foreground">Up to 50 schedules. Missed runs are not replayed, and each tick checks the current time window.</p>
  </div>;
}