import React from 'react';
import { Monitor, Globe, Cpu, Check, ArrowRight, ShieldCheck } from 'lucide-react';
import BrandButton from '@/components/operator/BrandButton';
import { sourcePackages } from '@/components/operator/sourcePackages';
import DevicePanel from '@/components/operator/DevicePanel';
export default function SystemsPanel({ onSources, data }) {
  return <div className="space-y-6"><DevicePanel data={data}/>
    <div className="grid md:grid-cols-2 gap-6">{sourcePackages.map((source,i)=><article className="brand-board" key={source.id}><div className="flex items-start justify-between gap-3"><div className="brand-board-icon">{i===0?<Globe/>:<Cpu/>}</div><span className="neutral-pill">Source available</span></div><h3>{source.name}</h3><p>{source.description}</p><ul className="grid gap-3 my-6 text-sm text-muted-foreground"><li className="flex gap-2"><Check className="w-4 h-4 shrink-0 text-[#CCBB00]"/>{source.files} archive entries inspected</li><li className="flex gap-2"><Check className="w-4 h-4 shrink-0 text-[#CCBB00]"/>{source.runtime}</li></ul><p>{i===0?'The companion includes an adapter for this archive’s engine: create sessions, navigate, click, fill, scroll, and close sessions. Add your deployed engine address and key when downloading a pairing kit.':'The archive provides orchestration functions and autonomous-job definitions. They have not been imported wholesale or connected to an AI provider.'}</p><BrandButton variant="outline" className="mt-6" onClick={()=>onSources(source.id)}>Inspect system source<ArrowRight/></BrandButton></article>)}</div>
    <div className="flex gap-3 p-5 border rounded-xl text-sm text-muted-foreground"><ShieldCheck className="w-5 h-5 shrink-0"/><p>Only workspace administrators can create, view, change, or cancel operator tasks and schedules. No passwords, API keys, or device credentials are stored in these records.</p></div></div>;
}