import React, { useState } from 'react';
import { ListTodo, ChevronDown, ArrowRight, Monitor, Globe, Search } from 'lucide-react';
import BrandButton from '@/components/operator/BrandButton';
import { targetLabels } from '@/components/operator/sourcePackages';
export default function TaskList({ tasks, onCreate, onUpdate, busy, compact = false }) {
  const [filter,setFilter] = useState('all'), [search,setSearch] = useState('');
  const visible = tasks.filter(t => (filter === 'all' || t.status === filter) && `${t.title} ${t.instructions}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="operator-panel"><div className="flex flex-wrap items-center justify-between gap-4 p-6 border-b"><div><h2 className="font-bold text-base">{compact ? 'Recent tasks' : 'Task queue'}</h2><p className="text-xs text-muted-foreground mt-1">Saved goals, ready for a connected runtime.</p></div><span className="neutral-pill">{tasks.filter(t=>t.status==='queued').length} queued</span></div>
    {!compact && <div className="p-5 flex flex-wrap items-center justify-between gap-4"><div className="brand-tabs">{['all','queued','cancelled'].map(value=><label key={value}><input type="radio" name="task-status" value={value} checked={filter===value} onChange={()=>setFilter(value)}/><span className="capitalize">{value}</span></label>)}</div><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input aria-label="Search tasks" className="operator-input pl-9" placeholder="Search tasks" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>}
    {visible.length === 0 ? <div className="py-12 px-6 text-center"><div className="w-12 h-12 rounded-xl border mx-auto flex items-center justify-center mb-4 bg-muted"><ListTodo className="w-5 h-5 text-muted-foreground"/></div><h3 className="text-sm font-semibold">{tasks.length ? 'No matching tasks' : 'Make your first move'}</h3><p className="text-sm text-muted-foreground mt-2 mb-5">{tasks.length ? 'Try another filter or search.' : 'Give your agent a clear goal to work toward.'}</p>{!tasks.length&&<BrandButton variant="outline" onClick={onCreate}>Create a task<ArrowRight/></BrandButton>}</div> : <div className="divide-y">{(compact ? visible.slice(0,4) : visible).map(task=><details key={task.id} className="group"><summary className="list-none p-5 flex items-center gap-4"><div className="w-9 h-9 bg-muted border rounded-lg flex items-center justify-center shrink-0">{task.target==='computer'?<Monitor className="h-4 w-4"/>:<Globe className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold truncate">{task.title}</p><p className="text-xs text-muted-foreground mt-1">{targetLabels[task.target]} · {task.source === 'schedule' ? 'Scheduled' : 'Manual'} task</p></div><span className="neutral-pill capitalize">{task.status}</span><ChevronDown className="w-4 h-4 group-open:rotate-180"/></summary><div className="px-6 pb-5 sm:pl-[72px]"><p className="text-sm whitespace-pre-wrap break-words">{task.instructions}</p><p className="text-xs text-muted-foreground mt-3">Created {new Date(task.created_date).toLocaleString()} · {task.status==='queued'?'Waiting for an execution connection. No actions have run.':'This task will not be dispatched.'}</p>{task.status==='queued'&&<button disabled={busy} className="brand-link mt-4 underline" onClick={()=>window.confirm('Cancel this queued task?')&&onUpdate({id:task.id,status:'cancelled'})}>Cancel task</button>}</div></details>)}</div>}
    {!compact&&<div className="p-4 border-t text-xs text-muted-foreground">Showing the latest {tasks.length} tasks · Up to 200 recent tasks</div>}
  </section>;
}